from automata.fa.Moore import Moore
import sys, os
import string
from collections import defaultdict
import xml.etree.ElementTree as ET
from xml.dom import minidom
from myerror import MyError

error_handler = MyError('LexerErrors')

global check_cm
global check_key

alfabeto = list(string.ascii_lowercase + string.ascii_uppercase)

numeros = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']

caracter = ['\n', ' ', '(', ')', '[', ']', '{', '}', ';', ',', '+', '-', '/', '*', '=', '!', '<', '>']

fullList = alfabeto + numeros + caracter

# Definição dos estados do autômato de Moore
states = [
    'q0', 'qId', 'qId1', 'qNumber', 'qNumber1', 'qFinal', 
    'qLoop1', 'qO', 'qA', 'qT', 'qIf', 'qIf1', 
    'qElse1', 'qElse2', 'qElse3', 'qElse4', 
    'qInt1', 'qInt2', 'qInt3', 'qInt4', 
    'qReturn1', 'qReturn2', 'qReturn3', 'qReturn4', 'qReturn5', 'qReturn6',
    'qVoid1', 'qVoid2', 'qVoid3', 'qVoid4', 
    'qWhile', 'qH', 'qI', 'qL', 'qE', 
    'qAdd', 'qSubtract', 'qMultiply', 'qDivide', 
    'qLessThan', 'qLessEqual', 'qGreaterThan', 'qGreaterEqual', 
    'qEquals', 'qNotEqual', 'qLeftParen', 'qRightParen', 
    'qLeftBracket', 'qRightBracket', 'qLeftBrace', 'qRightBrace', 
    'qDoubleEquals', 'qSemicolon', 'qComma', 'qNotEqual1'
]

# Labels (saídas do autômato de Moore)
labels = [
    'INT', 'IF', 'ELSE', 'VOID', 'RETURN', 'WHILE', 'FLOAT', 
    'MINUS', 'PLUS', 'TIMES', 'DIVIDE', 'LESS', 'LESS_EQUAL', 
    'GREATER_EQUAL', 'GREATER', 'EQUALS', 'DIFFERENT', 
    'LPAREN', 'RPAREN', 'LBRACKETS', 'RBRACKETS', 
    'LBRACES', 'RBRACES', 'ATTRIBUTION', 'SEMICOLON', 'COMMA', 
    'NUMBER', 'ID'
]



transitions = {
    'q0': {
                'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qComma',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            id : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qInt1' : {
                'f' : 'qIf',
                'n' : 'qInt2',
                ##misc##
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\n' : 'q0',
                ' ' : 'qId',
                '\t' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qIf' : {
                #fim do if#
               '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qInt2' : {
                't' : 'qInt3',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qInt3' : {
              ## fim do int ##  
               '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qElse1' : {
                'l' : 'qElse2',
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qElse2' : {
                's' : 'qElse3',
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qElse3' : {
                'e' : 'qElse4',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qElse4' : {
                ## fim do else ##
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qReturn1' : {
                'e' : 'qReturn2',
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qReturn2' : {
                't' : 'qReturn3',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qReturn3' : {
                'u' : 'qReturn4',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qReturn4' : {
                'r': 'qReturn5',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qReturn5' : {
                'n': 'qReturn6',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qReturn6' : {
                #fim do return#
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qVoid1': {
                'o': 'qVoid2',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qVoid2' : {
                'i': 'qVoid3',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qVoid3' : {
                'd' : 'qVoid4',
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qVoid4' : {
                ##fim do void ##
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qWhile' : {
                'h': 'qH',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qH' : {
                'i': 'qI',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qI' : {
                'l': 'qL',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qL' : {
                'e' : 'qE',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qE' : {
                ## fim do while ##
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qFinal' : {
                'l' : 'qLoop1',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qLoop1' : {
                'o': 'qO',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qO' : {
                'a' : 'qA',
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qA' : {
                't' : 'qT',
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'qId',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qT' : { 
                ## fim do float##
                 '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qSubtract' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qAdd' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qMultiply' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qDivide' : {
        'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qLessThan' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=':  'qLessThanEqual',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qLessThanEqual' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qGreaterThan' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qGreaterThanIgual',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qGreaterThanIgual' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qEquals' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEqualsIgual',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qEqualsIgual' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qNotEqual' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qNotEqual1',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qNotEqual1' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qLeftParen' : {
                'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qRightParen' : {
                'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qLeftBrace' : {
                'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            }, 
            'qRightBrace' : {
                'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            }, 
            'qLeftBracket' : {
                'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qRightBracket' : {
                'i': 'qInt1',
                'e': 'qElse1',
                'f': 'qFinal',
                'r': 'qReturn1',
                'v': 'qVoid1',
                'w': 'qWhile',
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'g': 'qId',
                'h': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qSemicolon' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qDot' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qId' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId1',
                'b': 'qId1',
                'c': 'qId1',
                'd': 'qId1',
                'e': 'qId1',
                'f': 'qId1',
                'g': 'qId1',
                'h': 'qId1',
                'i': 'qId1',
                'j': 'qId1',
                'k': 'qId1',
                'l': 'qId1',
                'm': 'qId1',
                'n': 'qId1',
                'o': 'qId1',
                'p': 'qId1',
                'q': 'qId1',
                'r': 'qId1',
                's': 'qId1',
                't': 'qId1',
                'u': 'qId1',
                'v': 'qId1',
                'w': 'qId1',
                'x': 'qId1',
                'y': 'qId1',
                'z' : 'qId1',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qId1' : {
            ## fim do ID
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId1',
                'b': 'qId1',
                'c': 'qId1',
                'd': 'qId1',
                'e': 'qId1',
                'f': 'qId1',
                'g': 'qId1',
                'h': 'qId1',
                'i': 'qId1',
                'j': 'qId1',
                'k': 'qId1',
                'l': 'qId1',
                'm': 'qId1',
                'n': 'qId1',
                'o': 'qId1',
                'p': 'qId1',
                'q': 'qId1',
                'r': 'qId1',
                's': 'qId1',
                't': 'qId1',
                'u': 'qId1',
                'v': 'qId1',
                'w': 'qId1',
                'x': 'qId1',
                'y': 'qId1',
                'z' : 'qId1',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber',
                '2' : 'qNumber',
                '3' : 'qNumber',
                '4' : 'qNumber',
                '5' : 'qNumber',
                '6' : 'qNumber',
                '7' : 'qNumber',
                '8' : 'qNumber',
                '9' : 'qNumber',
                '0' : 'qNumber',
            },
            'qNumber' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber1',
                '2' : 'qNumber1',
                '3' : 'qNumber1',
                '4' : 'qNumber1',
                '5' : 'qNumber1',
                '6' : 'qNumber1',
                '7' : 'qNumber1',
                '8' : 'qNumber1',
                '9' : 'qNumber1',
                '0' : 'qNumber1',
            },
            'qNumber1' : {
                '+': 'qAdd',
                '-': 'qSubtract',
                '*': 'qMultiply',
                '/': 'qDivide',
                '<': 'qLessThan',
                '>': 'qGreaterThan',
                '=': 'qEquals',
                '!': 'qNotEqual',
                '(': 'qLeftParen',
                ')': 'qRightParen',
                '[': 'qLeftBracket',
                ']': 'qRightBracket',
                '{': 'qLeftBrace',
                '}': 'qRightBrace',
                ';': 'qSemicolon',
                ',': 'qDot',
                #id de letra#
                'a': 'qId',
                'b': 'qId',
                'c': 'qId',
                'd': 'qId',
                'e': 'qId',
                'f': 'qId',
                'g': 'qId',
                'h': 'qId',
                'i': 'qId',
                'j': 'qId',
                'k': 'qId',
                'l': 'qId',
                'm': 'qId',
                'n': 'qId',
                'o': 'qId',
                'p': 'qId',
                'q': 'qId',
                'r': 'qId',
                's': 'qId',
                't': 'qId',
                'u': 'qId',
                'v': 'qId',
                'w': 'qId',
                'x': 'qId',
                'y': 'qId',
                'z' : 'qId',
                ##padrao##
                '\t' : 'q0',
                '\n' : 'q0',
                ' ' : 'q0',
                ##numeros##
                '1' : 'qNumber1',
                '2' : 'qNumber1',
                '3' : 'qNumber1',
                '4' : 'qNumber1',
                '5' : 'qNumber1',
                '6' : 'qNumber1',
                '7' : 'qNumber1',
                '8' : 'qNumber1',
                '9' : 'qNumber1',
                '0' : 'qNumber1',
            }
}

# Estado inicial da máquina
initial_state = "q0"

# Tabela de saída para os estados
output_table = {
    'q0': '',
    'qId': 'ID\n',
    'qId1': '',
    'qNumber': 'NUMBER\n',
    'qNumber1': '',
    'qFinal': '',
    'qLoop1': '',
    'qO': '',
    'qA': '',
    'qT': 'FLOAT\n',
    'qIf': '',
    'qIf1': 'IF\n',
    'qElse1': '',
    'qElse2': '',
    'qElse3': '',
    'qElse4': 'ELSE\n',
    'qInt1': '',
    'qInt2': '',
    'qInt3': 'INT\n',
    'qReturn1': '',
    'qReturn2': '',
    'qReturn3': '',
    'qReturn4': '',
    'qReturn5': '',
    'qReturn6': 'RETURN\n',
    'qVoid1': '',
    'qVoid2': '',
    'qVoid3': '',
    'qVoid4': 'VOID\n',
    'qWhile': '',
    'qH': '',
    'qI': '',
    'qL': '',
    'qE': 'WHILE\n',
    'qAdd': 'PLUS\n',
    'qSubtract': 'MINUS\n',
    'qMultiply': 'TIMES\n',
    'qDivide': 'DIVIDE\n',
    'qLessThan': 'LESS\n',
    'qLessThanEqual': 'LESS_EQUAL\n',
    'qGreaterThan': 'GREATER\n',
    'qGreaterThanEqual': 'GREATER_EQUAL\n',
    'qEquals': 'ATTRIBUTION\n',
    'qNotEqual': '',
    'qLeftParen': 'LPAREN\n',
    'qRightParen': 'RPAREN\n',
    'qLeftBracket': 'LBRACKETS\n',
    'qRightBracket': 'RBRACKETS\n',
    'qLeftBrace': 'LBRACES\n',
    'qRightBrace': 'RBRACES\n',
    'qEqualsEqual': 'EQUALS\n',
    'qSemicolon': 'SEMICOLON\n',
    'qDot': 'COMMA\n',
    'qNotEqual1': 'DIFFERENT\n'
}

# Instância do autômato de Moore
moore = Moore(
    states,
    fullList,
    labels,
    transitions,
    initial_state,
    output_table
)


def main():
    check_cm = False
    check_key = False

    if len(sys.argv) < 2:
        raise TypeError(error_handler.newError(check_key, 'ERR-LEX-USE'))

    for idx, arg in enumerate(sys.argv):
        file_extension = arg.split('.')
        if file_extension[-1] == 'cm':
            check_cm = True
            idx_cm = idx

        if arg == "-k":
            check_key = True

    if check_key and len(sys.argv) < 3:
        raise TypeError(error_handler.newError(check_key, 'ERR-LEX-USE'))
    elif not check_cm:
        raise IOError(error_handler.newError(check_key, 'ERR-LEX-NOT-CM'))
    elif not os.path.exists(sys.argv[idx_cm]):
        raise IOError(error_handler.newError(check_key, 'ERR-LEX-FILE-NOT-EXISTS'))
    else:
        with open(sys.argv[idx_cm], 'r') as file:
            source_file = file.read()

        try:
            if not check_key:
                print("Definição da Máquina:")
                print(moore)
                print("Entrada:")
                print(source_file)
                print("Lista de Tokens:")

            print(moore.get_output_from_string(source_file).rstrip('\n'))

            moore_to_jflap(states, full_char_list, labels, transitions, initial_state, output_table, 'machine.jff')

        except Exception as e:
            error_msg = str(e)

            # Identifica o caractere que gerou o erro
            for i, char in enumerate(source_file):
                try:
                    moore.get_output_from_string(source_file[:i+1])  # Testa até o caractere atual
                except Exception:
                    error_index = i
                    break
            else:
                error_index = None  # Caso não encontre o erro

            if error_index is not None:
                # Localiza a linha e a coluna do erro
                line = source_file[:error_index].count('\n') + 1
                last_newline = source_file[:error_index].rfind('\n')
                column = (error_index - last_newline) if last_newline != -1 else error_index + 1
                raise IOError(error_handler.newError(check_key, 'ERR-LEX-INV-CHAR', line, column, valor=e))
            else:
                line, column = "Desconhecido", "Desconhecido"


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e)
    except (ValueError, TypeError):
        print(e)
